import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { useEffect, useState } from 'react';
import { RecoilRoot} from 'recoil'; 
import Blogs from '../compoenents/blogs/blogs';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const [authenticated, setAuthenticated] = useState<boolean>(true);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
      <RecoilRoot>
        <main className={styles.main}>
          {authenticated? <Blogs/>: <Login setAuthenticated={setAuthenticated}/>
          }
        </main>
    </RecoilRoot>
      </main>
    </>
  )
}
